# Generated by Django 3.0.2 on 2020-01-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='post',
            name='course_slug',
            field=models.SlugField(default='null', max_length=200),
        ),
    ]
