# Generated by Django 3.0.2 on 2020-01-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0003_auto_20200116_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='popular',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
