# Generated by Django 3.0.2 on 2020-01-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0004_category_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='headshots/'),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='Enter email here', max_length=254),
        ),
    ]
