# Generated by Django 3.0.2 on 2020-01-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0006_auto_20200122_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='description', null=True),
        ),
    ]
