# Generated by Django 3.0.2 on 2020-01-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0007_auto_20200122_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
